[language-server.markdown]
command = "/sbin/marksman"

[[language]]
name = "c"
indent = { tab-width = 8, unit = "    " }

[[language]]
name = "cpp"
indent = { tab-width = 8, unit = "    " }

[[language]]
name = "markdown"
indent = { tab-width = 8, unit = "    " }
